version: '3.8'

services:
  pwa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saberloop
    ports:
      - "443:443"
    restart: unless-stopped

  php-api:
    build:
      context: ./php-api
      dockerfile: Dockerfile
    container_name: quiz-php-api
    ports:
      - "8080:80"
    volumes:
      - ./php-api:/var/www/html
    working_dir: /var/www/html